import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { CreditCard, Smartphone, Wallet, AlertCircle, CheckCircle, Loader2 } from 'lucide-react';
import { paymentService } from '../../services/paymentService';

const PaymentFormSchema = z.object({
  paymentMethod: z.enum(['MPESA', 'STRIPE_CARD', 'WALLET']),
  phoneNumber: z.string().regex(/^254[0-9]{9}$/, 'Invalid Kenyan phone number format').optional(),
  cardNumber: z.string().min(16, 'Invalid card number').optional(),
  expiryDate: z.string().regex(/^(0[1-9]|1[0-2])\/[0-9]{2}$/, 'Format: MM/YY').optional(),
  cvv: z.string().min(3, 'Invalid CVV').max(4, 'Invalid CVV').optional(),
  cardholderName: z.string().min(2, 'Cardholder name required').optional(),
}).refine((data) => {
  if (data.paymentMethod === 'MPESA' && !data.phoneNumber) {
    return false;
  }
  if (data.paymentMethod === 'STRIPE_CARD' && (!data.cardNumber || !data.expiryDate || !data.cvv || !data.cardholderName)) {
    return false;
  }
  return true;
}, {
  message: 'Required payment details missing',
});

type PaymentFormData = z.infer<typeof PaymentFormSchema>;

interface PaymentProcessorProps {
  bookingId: string;
  amount: number;
  serviceTitle: string;
  onSuccess: () => void;
  onCancel: () => void;
  isEmergency?: boolean;
}

export const PaymentProcessor: React.FC<PaymentProcessorProps> = ({
  bookingId,
  amount,
  serviceTitle,
  onSuccess,
  onCancel,
  isEmergency = false
}) => {
  const [processing, setProcessing] = useState(false);
  const [paymentStatus, setPaymentStatus] = useState<'idle' | 'processing' | 'success' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState('');
  const [selectedMethod, setSelectedMethod] = useState<'MPESA' | 'STRIPE_CARD' | 'WALLET'>('MPESA');

  const {
    register,
    handleSubmit,
    formState: { errors },
    setValue
  } = useForm<PaymentFormData>({
    resolver: zodResolver(PaymentFormSchema),
    defaultValues: {
      paymentMethod: 'MPESA'
    }
  });

  // const paymentMethod = watch('paymentMethod');

  const handlePaymentMethodChange = (method: 'MPESA' | 'STRIPE_CARD' | 'WALLET') => {
    setSelectedMethod(method);
    setValue('paymentMethod', method);
    setPaymentStatus('idle');
    setErrorMessage('');
  };

  const processPayment = async (data: PaymentFormData) => {
    try {
      setProcessing(true);
      setPaymentStatus('processing');
      setErrorMessage('');

      let result;

      switch (data.paymentMethod) {
        case 'MPESA':
          result = await paymentService.initiateMpesaPayment({
            bookingId,
            phoneNumber: data.phoneNumber!,
            amount,
            isEmergency
          });
          break;

        case 'STRIPE_CARD':
          // In a real implementation, you would tokenize the card first
          result = await paymentService.initiateStripePayment({
            bookingId,
            cardToken: 'mock_card_token', // This would be generated by Stripe.js
            amount,
            isEmergency
          });
          break;

        case 'WALLET':
          result = await paymentService.processPayment({
            bookingId,
            paymentMethod: 'WALLET',
            amount,
            isEmergency
          });
          break;

        default:
          throw new Error('Invalid payment method');
      }

      if (result.success) {
        setPaymentStatus('success');
        setTimeout(() => {
          onSuccess();
        }, 2000);
      } else {
        setPaymentStatus('error');
        setErrorMessage(result.message || 'Payment failed');
      }
    } catch (error) {
      setPaymentStatus('error');
      setErrorMessage('Payment processing failed. Please try again.');
      console.error('Payment error:', error);
    } finally {
      setProcessing(false);
    }
  };

  const renderPaymentMethodContent = () => {
    switch (selectedMethod) {
      case 'MPESA':
        return (
          <div className="space-y-4">
            <div className="flex items-center space-x-3 p-4 bg-green-50 border border-green-200 rounded-lg">
              <Smartphone className="h-8 w-8 text-green-600" />
              <div>
                <h3 className="font-semibold text-green-800">M-Pesa Payment</h3>
                <p className="text-sm text-green-600">Pay using your M-Pesa mobile money</p>
              </div>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                M-Pesa Phone Number
              </label>
              <input
                {...register('phoneNumber')}
                type="tel"
                placeholder="254700000000"
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              {errors.phoneNumber && (
                <p className="mt-1 text-sm text-red-600">{errors.phoneNumber.message}</p>
              )}
            </div>

            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-sm text-blue-800">
                <strong>Instructions:</strong>
                <br />
                1. Enter your M-Pesa registered phone number
                <br />
                2. Click "Pay with M-Pesa" 
                <br />
                3. Enter your M-Pesa PIN when prompted
              </p>
            </div>
          </div>
        );

      case 'STRIPE_CARD':
        return (
          <div className="space-y-4">
            <div className="flex items-center space-x-3 p-4 bg-blue-50 border border-blue-200 rounded-lg">
              <CreditCard className="h-8 w-8 text-blue-600" />
              <div>
                <h3 className="font-semibold text-blue-800">Credit/Debit Card</h3>
                <p className="text-sm text-blue-600">Pay securely with your card</p>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Card Number
              </label>
              <input
                {...register('cardNumber')}
                type="text"
                placeholder="1234 5678 9012 3456"
                maxLength={19}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              {errors.cardNumber && (
                <p className="mt-1 text-sm text-red-600">{errors.cardNumber.message}</p>
              )}
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Expiry Date
                </label>
                <input
                  {...register('expiryDate')}
                  type="text"
                  placeholder="MM/YY"
                  maxLength={5}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                {errors.expiryDate && (
                  <p className="mt-1 text-sm text-red-600">{errors.expiryDate.message}</p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  CVV
                </label>
                <input
                  {...register('cvv')}
                  type="text"
                  placeholder="123"
                  maxLength={4}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                {errors.cvv && (
                  <p className="mt-1 text-sm text-red-600">{errors.cvv.message}</p>
                )}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Cardholder Name
              </label>
              <input
                {...register('cardholderName')}
                type="text"
                placeholder="John Doe"
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              {errors.cardholderName && (
                <p className="mt-1 text-sm text-red-600">{errors.cardholderName.message}</p>
              )}
            </div>
          </div>
        );

      case 'WALLET':
        return (
          <div className="space-y-4">
            <div className="flex items-center space-x-3 p-4 bg-purple-50 border border-purple-200 rounded-lg">
              <Wallet className="h-8 w-8 text-purple-600" />
              <div>
                <h3 className="font-semibold text-purple-800">Wakili Wallet</h3>
                <p className="text-sm text-purple-600">Pay from your wallet balance</p>
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg">
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-600">Current Balance:</span>
                <span className="font-semibold text-gray-800">KES 0.00</span>
              </div>
            </div>

            <div className="bg-yellow-50 p-4 rounded-lg">
              <p className="text-sm text-yellow-800">
                <strong>Note:</strong> Insufficient wallet balance. 
                <br />
                Add funds to your wallet to use this payment method.
              </p>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  const renderPaymentStatus = () => {
    switch (paymentStatus) {
      case 'processing':
        return (
          <div className="text-center py-8">
            <Loader2 className="h-12 w-12 animate-spin text-blue-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-800">Processing Payment</h3>
            <p className="text-gray-600">Please wait while we process your payment...</p>
            {selectedMethod === 'MPESA' && (
              <p className="text-sm text-blue-600 mt-2">Check your phone for M-Pesa prompt</p>
            )}
          </div>
        );

      case 'success':
        return (
          <div className="text-center py-8">
            <CheckCircle className="h-12 w-12 text-green-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-green-800">Payment Successful!</h3>
            <p className="text-gray-600">Your booking has been confirmed.</p>
          </div>
        );

      case 'error':
        return (
          <div className="text-center py-8">
            <AlertCircle className="h-12 w-12 text-red-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-red-800">Payment Failed</h3>
            <p className="text-gray-600 mb-4">{errorMessage}</p>
            <button
              onClick={() => {
                setPaymentStatus('idle');
                setErrorMessage('');
              }}
              className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700"
            >
              Try Again
            </button>
          </div>
        );

      default:
        return null;
    }
  };

  if (paymentStatus === 'processing' || paymentStatus === 'success' || paymentStatus === 'error') {
    return (
      <div className="max-w-md mx-auto bg-white rounded-lg shadow-lg p-6">
        {renderPaymentStatus()}
        {paymentStatus === 'success' && (
          <div className="text-center mt-4">
            <button
              onClick={onSuccess}
              className="bg-green-600 text-white px-6 py-2 rounded-md hover:bg-green-700"
            >
              Continue
            </button>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="max-w-md mx-auto bg-white rounded-lg shadow-lg p-6">
      <div className="mb-6">
        <h2 className="text-xl font-semibold text-gray-800 mb-2">Complete Payment</h2>
        <div className="bg-gray-50 p-4 rounded-lg">
          <p className="text-sm text-gray-600">Service: <span className="font-semibold">{serviceTitle}</span></p>
          <p className="text-lg font-bold text-gray-800">Amount: KES {amount.toLocaleString()}</p>
        </div>
      </div>

      {/* Payment Method Selection */}
      <div className="mb-6">
        <h3 className="text-sm font-medium text-gray-700 mb-3">Choose Payment Method</h3>
        <div className="grid grid-cols-3 gap-2">
          <button
            type="button"
            onClick={() => handlePaymentMethodChange('MPESA')}
            className={`p-3 border rounded-lg text-center transition-colors ${
              selectedMethod === 'MPESA'
                ? 'border-green-500 bg-green-50 text-green-700'
                : 'border-gray-300 hover:border-green-500'
            }`}
          >
            <Smartphone className="h-6 w-6 mx-auto mb-1" />
            <span className="text-xs">M-Pesa</span>
          </button>

          <button
            type="button"
            onClick={() => handlePaymentMethodChange('STRIPE_CARD')}
            className={`p-3 border rounded-lg text-center transition-colors ${
              selectedMethod === 'STRIPE_CARD'
                ? 'border-blue-500 bg-blue-50 text-blue-700'
                : 'border-gray-300 hover:border-blue-500'
            }`}
          >
            <CreditCard className="h-6 w-6 mx-auto mb-1" />
            <span className="text-xs">Card</span>
          </button>

          <button
            type="button"
            onClick={() => handlePaymentMethodChange('WALLET')}
            className={`p-3 border rounded-lg text-center transition-colors ${
              selectedMethod === 'WALLET'
                ? 'border-purple-500 bg-purple-50 text-purple-700'
                : 'border-gray-300 hover:border-purple-500'
            }`}
          >
            <Wallet className="h-6 w-6 mx-auto mb-1" />
            <span className="text-xs">Wallet</span>
          </button>
        </div>
      </div>

      {/* Payment Form */}
      <form onSubmit={handleSubmit(processPayment)} className="space-y-6">
        {renderPaymentMethodContent()}

        <div className="flex space-x-4 pt-4">
          <button
            type="button"
            onClick={onCancel}
            className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={processing || selectedMethod === 'WALLET'}
            className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
          >
            {processing ? 'Processing...' : `Pay KES ${amount.toLocaleString()}`}
          </button>
        </div>
      </form>
    </div>
  );
};